AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys the Auto CSR Stack (Agent and Email Poller)

Parameters:
  CodeBucket:
    Type: String
    Description: S3 bucket where Lambda code is stored

  CodeKey:
    Type: String
    Description: Path to Lambda zip in S3

Resources:
  CsrAgentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: csr-agent-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaLogging
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:StartQuery
                  - logs:GetQueryResults
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                Resource: "*"
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource: "*"

  CsrAgentFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: csr-agent
      Runtime: python3.10
      Handler: agent.new_email
      Role: !GetAtt CsrAgentRole.Arn
      Timeout: 30
      MemorySize: 128
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeKey
      Environment:
        Variables:
          INBOUND_EMAIL_BUCKET: !Ref TriggerBucket

  CsrAgentPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CsrAgentFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt TriggerBucket.Arn

  TriggerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: inbound-email-bucket
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt CsrAgentFunction.Arn
