name: Deploy Email Categorizer LLM
description: Deploys the Email Categorizer LLM to AWS using CloudFormation.

on:
  push:
    branches:
      - main
    paths:
      - 'email-categorizer/**'
      - '.github/workflows/deploy-email-categorizer.yaml'
  workflow_dispatch:

env:
  REGION: us-east-1
  STACK_NAME: email-categorizer-stack
  TEMPLATE_PATH: email-categorizer/template.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Deploy LLM via CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file ${{ env.TEMPLATE_PATH }} \
            --stack-name ${{ env.STACK_NAME }} \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ${{ env.REGION }}
