name: Deploy SES Lambda

on:
  push:
    paths:
      - 'infra/lambda/**'
      - 'infra/ses-email-processor.yaml'
      - '.github/workflows/deploy.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      S3_BUCKET: auto-csr-ses-lambda-bucket
      S3_KEY: lambda-package.zip
      STACK_NAME: ses-email-project
      REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Zip Lambda function
        run: |
          cd infra/lambda
          zip -r ../../lambda-package.zip .

      - name: Configure AWS CLI
        run: |
          pip install awscli

      - name: Upload Lambda package to S3
        run: |
          aws s3 cp lambda-package.zip s3://${{ env.S3_BUCKET }}/${{ env.S3_KEY }} --region ${{ env.REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.STACK_NAME }}
          template: infra/ses-email-processor.yaml
          no-fail-on-empty-changeset: true
          parameter-overrides: |
            VerifiedRecipientEmail=youremail@example.com
            ReplyFromEmail=youremail@example.com
            LambdaCodeS3Bucket=${{ env.S3_BUCKET }}
            LambdaCodeS3Key=${{ env.S3_KEY }}
        env:
          AWS_REGION: ${{ env.REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
