name: Deploy Email Poller Lambda
description: Deploys the Email Poller Lambda function to AWS using CloudFormation.

on:
  workflow_dispatch:

env:
  REGION: us-east-1
  STACK_NAME: email-poller-stack
  BUCKET_NAME: auto-csr-lambda-code
  CODE_KEY: email-poller/email-poller.zip
  TEMPLATE_PATH: email-poller/template.yaml
  ZIP_PATH: email-poller.zip

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Lambda source code
        run: |
          cd email-poller
          zip ../${ZIP_PATH} main.py config.py gmail_client.py
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Create bucket if it doesn't exist
        run: |
          if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket does not exist. Creating: $BUCKET_NAME"
            if [ "$REGION" = "us-east-1" ]; then
              aws s3api create-bucket \
                --bucket "$BUCKET_NAME"
            else
              aws s3api create-bucket \
                --bucket "$BUCKET_NAME" \
                --region "$REGION" \
                --create-bucket-configuration LocationConstraint="$REGION"
            fi
          else
            echo "Bucket already exists: $BUCKET_NAME"
          fi

      - name: Upload Lambda zip to S3
        run: |
          aws s3 cp $ZIP_PATH s3://$BUCKET_NAME/$CODE_KEY

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file $TEMPLATE_PATH \
            --parameter-overrides \
              CodeBucket=$BUCKET_NAME \
              CodeKey=$CODE_KEY \
            --capabilities CAPABILITY_NAMED_IAM
